import { useNavigate } from "react-router-dom";
import Breadcrumbs from "../../../../components/ui/Breadcrumbs";
import BlocksGap from "../../../../components/common/BlocksGap";
import MainTitleCollections from "../../../../components/common/MainTitleCollections";
import HeadCollection from "../../../../components/common/HeadCollection";
import BoxesFooter from "../../../../components/common/BoxesFooter";

// interface IProduct {
//   id: number;
//   image: string;
//   title: string;
//   code?: string;
//   link?: string;
//   type?: "normal" | "special";
//   collections?: string;
// }

const sections = [
  {
    id: 1,
    title: "Easy Steam",
    description:
      "By evaporating water inside the oven, the Easy Steam function helps food to be better cooked compared to the same cooking without the addition of humidity.",
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2022/02/elba-easy-steam-oven.jpg.webp",
  },
  {
    id: 2,
    title: "Idroclean",
    description:
      "Without using any type of detergent, this function helps remove the dirt inside the oven thanks to the moisture generated by the water warming at 80-90°C.",
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2022/02/elba-idroclean-oven.jpg.webp",
  },
];



const AlterumOvens = () => {
  const navigate = useNavigate();
  return (
    <div>
      <HeadCollection image="https://www.elba-cookers.com/wp-content/uploads/2022/03/elba-alterum-collection-oven.jpg.webp" />
            <div className="container  relative z-5 pt-[580px] pb-20 space-y-8">
        <div className="flex items-center justify-between">
          <Breadcrumbs
            linkColor={"#000000"}
            activeColor={"#000000"}
            separatorColor={"#000000"}
          />
          <button
            onClick={() => navigate(-1)}
            className="text-xl font-bold cursor-pointer"
          >
            Back_
          </button>
        </div>

        <MainTitleCollections title="Alterum Collection. Minimalist lines in a sober style">
        <p>Alterum Collection has simple, minimalist lines in an exclusive style; an elegant and sober design.</p>
        </MainTitleCollections>

        <BlocksGap sections={sections} />

       <BoxesFooter />
      </div>
    </div>
  );
};

export default AlterumOvens;
