import { useNavigate } from "react-router-dom";
import Breadcrumbs from "../../../../components/ui/Breadcrumbs";
import BlocksGap from "../../../../components/common/BlocksGap";
import DiscoverTheCollection from "../../../../components/common/DiscoverTheCollection";
import MainTitleCollections from "../../../../components/common/MainTitleCollections";
import HeadCollection from "../../../../components/common/HeadCollection";
import { Helmet } from "react-helmet-async";

interface IProduct {
  id: number;
  image: string;
  title: string;
  code?: string;
  link?: string;
  type?: "normal" | "special";
  collections?: string;
}

const sections = [
  {
    id: 1,
    title: "Unmistakable country aesthetic",
    description:
      "The country aesthetic is enhanced by the characteristic knobs, all rigorously in antiqued brass; the gold-colored serigraphies reproduce an old-fashion design in balance between tradition and innovation.",
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2022/02/elba-country-control-panel.jpg.webp",
  },
  {
    id: 2,
    title: "Idroclean",
    description:
      "Without using any type of detergent, this function helps remove the dirt inside the oven thanks to the moisture generated by the water warming at 80-90°C.",
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2023/05/idroclean-elba-900x600px-elba.jpg.webp",
  },
];

const products: IProduct[] = [
  {
    id: 1,
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2022/03/elba-country-electric-multifunction-oven-ecm-9-lan-front.jpg.webp",
    title: "Electric multifunction oven",
    code: "ECM 9 LAN",
  },
  {
    id: 2,
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2022/03/elba-country-electric-multifunction-oven-ecm-9-lav.png.webp",
    title: "Electric multifunction oven",
    code: "ECM 9 LAV",
  },
  {
    id: 3,
    type: "special",
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2022/05/Country-1_500x700.jpg.webp",
    title: "Find out more",
    link: "/home",
    collections: "Country",
  },
];

const CountryOvens = () => {
  const navigate = useNavigate();
  return (
 <>
 <Helmet>
  <title>Country Built-in Ovens | BULM Italy</title>
  <meta
    name="description"
    content="Explore BULM’s Country Collection of built-in ovens — rustic, timeless design blended with modern performance. Discover electric multifunction ovens featuring Idroclean and traditional country style."
  />
  <meta
    name="keywords"
    content="Country ovens, BULM, built-in ovens, rustic ovens, traditional kitchen appliances, Idroclean, electric multifunction oven, country chic style"
  />
  <meta property="og:title" content="Country Built-in Ovens | BULM Italy" />
  <meta
    property="og:description"
    content="Inspired by tradition, the Country Collection by BULM offers timeless built-in ovens with elegant brass details and easy-clean Idroclean function."
  />
  <meta
    property="og:image"
    content="https://www.elba-cookers.com/wp-content/uploads/2022/03/Country-collection.jpg.webp"
  />
  <meta property="og:type" content="website" />
  <meta
    property="og:url"
    content="https://bulm.it/collections/collections-ovens/country-ovens"
  />
  <link
    rel="canonical"
    href="https://bulm.it/collections/collections-ovens/country-ovens"
  />
</Helmet>
 <div>
      <HeadCollection image="https://www.elba-cookers.com/wp-content/uploads/2022/03/Country-collection.jpg.webp" />
            <div className="container  relative z-5 pt-[580px] pb-20 space-y-8">
        <div className="flex items-center justify-between">
          <Breadcrumbs
            linkColor={"#000000"}
            activeColor={"#000000"}
            separatorColor={"#000000"}
          />
          <button
            onClick={() => navigate(-1)}
            className="text-xl font-bold cursor-pointer"
          >
            Back_
          </button>
        </div>

        <MainTitleCollections title="Country Collection. Inspired by tradition">
          <p>
            For those who love a touch of "Country Chic" style in the kitchen
            and prefer the nuances of material coulors,{" "}
            <strong>Country Collection built-in ovens</strong> are the ideal
            solution, giving the interior spaces the atmosphere that especially
            recalls the houses of the countryside.
          </p>
        </MainTitleCollections>

        <BlocksGap sections={sections} />

        <DiscoverTheCollection products={products} />
      </div>
    </div></>
  );
};

export default CountryOvens;
