import { useNavigate } from "react-router-dom";
import Breadcrumbs from "../../../../components/ui/Breadcrumbs";
import BlocksGap from "../../../../components/common/BlocksGap";
import DiscoverTheCollection from "../../../../components/common/DiscoverTheCollection";
import MainTitleCollections from "../../../../components/common/MainTitleCollections";
import HeadCollection from "../../../../components/common/HeadCollection";
import { Helmet } from "react-helmet-async";

interface IProduct {
  id: number;
  image: string;
  title: string;
  code?: string;
  link?: string;
  type?: "normal" | "special";
  collections?: string;
}

const sections = [
  {
    id: 1,
    title: "Large oven cavity",
    description:
      "74 usable litres (86 gross litres), with 7 levels positioning side racks, perfect for your multilevel preparations.",
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2022/02/elba-maxi-cavity-74-litres.jpg.webp",
  },
  {
    id: 2,
    title: "Easy Steam",
    description:
      "By evaporating water inside the oven, the Easy Steam function helps food to be better cooked adding the right degree of humidity.",
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2023/05/easysteam-elba-900x600px-elba.jpg.webp",
  },
  {
    id: 3,
    title: "Gas-matik hob",
    description:
      "Enzo gas-matik hob has a range of additional features: each gas burner can be programmed to turn off after a set period of time or set as a minute minder. Furthermore, this hob features a child lock function and if a burner is in use continuously for 4 hours, the system will automatically shut down. Available in 90cm size.",
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2022/02/elba-elio-gas-matik-hobs.jpg.webp",
  },
  {
    id: 4,
    title: "Idroclean",
    description:
      "Without using any type of detergent, this function helps remove the dirt inside the oven thanks to the moisture generated by the water heating at 80-90°C.",
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2023/05/idroclean-elba-900x600px-elba.jpg.webp",
  },
];

const products: IProduct[] = [
  {
    id: 1,
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2023/06/elba-elio-electric-multifunction-oven-el-11-xlb-300_front-on.jpg.webp",
    title: "Enzo electric multifunction oven",
    code: "EN 11 XLB 300",
  },
  {
    id: 2,
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2022/03/elba-elio-electric-multifunction-oven-el-10-xlx-300.png.webp",
    title: "Electric multifunction oven",
    code: "EN 10 XLX 300",
  },
  {
    id: 3,
    type: "special",
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2023/06/Elio_500x700_new.jpg.webp",
    title: "Find out more",
    link: "/home",
    collections: "Enzo",
  },
];

const EnzoOvens = () => {
  const navigate = useNavigate();
  return (
   <>
     <Helmet>
      <title>Enzo Built-in Ovens | BULM Italy</title>
      <meta
        name="description"
        content="Discover the Enzo built-in oven collection from BULM – featuring Easy Steam, Idroclean, and Gas-Matik functions. Sleek design and exceptional performance in every bake."
      />
      <meta
        name="keywords"
        content="Enzo ovens, BULM built-in ovens, multifunction ovens, electric ovens, Easy Steam oven, Idroclean oven, Gas-Matik, Italian kitchen appliances"
      />
      <meta property="og:title" content="Enzo Built-in Ovens | BULM Italy" />
      <meta
        property="og:description"
        content="Experience seamless design and innovative cooking with BULM’s Enzo built-in ovens. Crafted for performance with cutting-edge features like Easy Steam and Idroclean."
      />
      <meta
        property="og:image"
        content="https://www.elba-cookers.com/wp-content/uploads/2022/03/elba-elio-collection-oven.jpg.webp"
      />
      <meta property="og:type" content="website" />
      <meta
        property="og:url"
        content="https://bulm.it/collections/collections-ovens/enzo-ovens"
      />
      <link
        rel="canonical"
        href="https://bulm.it/collections/collections-ovens/enzo-ovens"
      />
    </Helmet>

    <div>
      <HeadCollection image="https://www.elba-cookers.com/wp-content/uploads/2022/03/elba-elio-collection-oven.jpg.webp" />
      <div className="container  relative z-5 pt-[580px] pb-20 space-y-8">
        <div className="flex items-center justify-between">
          <Breadcrumbs
            linkColor={"#000000"}
            activeColor={"#000000"}
            separatorColor={"#000000"}
          />
          <button
            onClick={() => navigate(-1)}
            className="text-xl font-bold cursor-pointer"
          >
            Back_
          </button>
        </div>

        <MainTitleCollections title="Enzo Collection. Seamless integration between style and efficiency">
          <p>
            Innovation and appeal are revealed in the{" "}
            <strong>Enzo built-in models</strong>. Top-quality materials,
            designed with the latest generation technology, such as{" "}
            <strong>Easy Steam</strong> and<strong> Idroclean</strong>{" "}
            functions, ensure high performances and excellent cooking results.{" "}
            <strong>Enzo Collection</strong> has simple, ergonomic lines in an
            exclusive style.
          </p>
        </MainTitleCollections>

        <BlocksGap sections={sections} />

        <DiscoverTheCollection products={products} />
      </div>
    </div>
   </>
  );
};

export default EnzoOvens;
