import { useNavigate } from "react-router-dom";
import Breadcrumbs from "../../../../components/ui/Breadcrumbs";
import BlocksGap from "../../../../components/common/BlocksGap";
import DiscoverTheCollection from "../../../../components/common/DiscoverTheCollection";
import MainTitleCollections from "../../../../components/common/MainTitleCollections";
import HeadCollection from "../../../../components/common/HeadCollection";
import { Helmet } from "react-helmet-async";

interface IProduct {
  id: number;
  image: string;
  title: string;
  code?: string;
  link?: string;
  type?: "normal" | "special";
  collections?: string;
}

const sections = [
  {
    id: 1,
    title: "Easy Steam",
    description:
      "Easy Steam By evaporating water inside the oven, the Easy Steam function helps food to be better cooked compared to the same cooking without the addition of humidity.",
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2022/02/elba-elio-collection-hobs.jpg.webp",
  },
  {
    id: 2,
    title: "Idroclean",
    description:
      "Without using any type of detergent, this function helps remove the dirt inside the oven thanks to the moisture generated by the water warming at 80-90°C.",
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2022/02/elba-idroclean-oven.jpg.webp",
  },
  {
    id: 3,
    title: "Leavening 40°C",
    description:
      "Built to last and to deal with the demands of daily cooking, these high specification ovens feature the function of Leavening at 40°C by which the dough maintains its characteristics, allowing optimal leavening.",
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2022/02/elba-leavening-40.jpg.webp",
  },
  {
    id: 4,
    title: "Special function Pizza300°C",
    description:
      "The exclusive Pizza special function with its 300°C allows you to cook your pizza perfectly as in a real professional oven. The upper heating element and the fan turn on. The heat coming from the bottom is diffused by forced convection.",
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2022/02/elba-pizza-300.jpg.webp",
  },
  {
    id: 5,
    title: "Large oven cavity",
    description:
      "74 usable liters (86 gross liters) with 7 levels with easier to remove side racks for your multilevel preparations.",
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2022/02/elba-maxi-cavity-74-litres.jpg.webp",
  },
];

const products: IProduct[] = [
  {
    id: 1,
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2022/03/elba-professional-electric-multifunction-oven-pro-9-xla.png.webp",
    title: "Electric multifunction oven",
    code: "EX 9 XLA",
  },
  {
    id: 2,
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2022/03/elba-professional-electric-multifunction-oven-pro-9-xlx.png.webp",
    title: "Electric multifunction oven",
    code: "EX 9 XLX",
  },
  {
    id: 3,
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2022/03/elba-professional-electric-multifunction-oven-pro-11-xlx.png.webp",
    title: "Electric multifunction oven",
    code: "EX 11 XLX",
  },
  {
    id: 4,
    type: "special",
    image:
      "https://www.elba-cookers.com/wp-content/uploads/2022/05/Professional_500x700.jpg.webp",
    title: "Find out more",
    link: "/home",
    collections: "Expert",
  },
];

const ExpertOvens = () => {
  const navigate = useNavigate();
  return (
    <>
      <Helmet>
        <title>Expert Built-in Ovens | BULM Italy</title>
        <meta
          name="description"
          content="Explore BULM's Expert built-in ovens collection – high-performance ovens with premium features like Easy Steam, Idroclean, Pizza300°C, and Leavening 40°C."
        />
        <meta
          name="keywords"
          content="Expert ovens, BULM built-in ovens, electric multifunction oven, Easy Steam, Idroclean, Pizza 300°C, Leavening 40°C, large oven cavity, Italian kitchen appliances"
        />
        <meta
          property="og:title"
          content="Expert Built-in Ovens | BULM Italy"
        />
        <meta
          property="og:description"
          content="Experience BULM’s Expert ovens – built for power, precision, and performance. Discover advanced cooking features for your modern kitchen."
        />
        <meta
          property="og:image"
          content="https://www.elba-cookers.com/wp-content/uploads/2023/01/elba-professional-ovens-collection-2.jpg.webp"
        />
        <meta property="og:type" content="website" />
        <meta
          property="og:url"
          content="https://bulm.it/collections/collections-ovens/expert-ovens"
        />
        <link
          rel="canonical"
          href="https://bulm.it/collections/collections-ovens/expert-ovens"
        />
      </Helmet>

      <div>
        <HeadCollection image="https://www.elba-cookers.com/wp-content/uploads/2023/01/elba-professional-ovens-collection-2.jpg.webp" />
        <div className="container  relative z-5 pt-[580px] pb-20 space-y-8">
          <div className="flex items-center justify-between">
            <Breadcrumbs
              linkColor={"#000000"}
              activeColor={"#000000"}
              separatorColor={"#000000"}
            />
            <button
              onClick={() => navigate(-1)}
              className="text-xl font-bold cursor-pointer"
            >
              Back_
            </button>
          </div>

          <MainTitleCollections title="Expert Collection. Professional performance for your kitchen">
            <p>
              The <strong>Expert collection</strong> offers professional
              performances for your kitchen at home. Its distinctive style
              features elegant knobs and ergonomically designed handles,
              capacity, flexibility and usability with dedicated special
              functions such as
              <strong> Easy Steam</strong> and <strong>Idroclean</strong>.
            </p>
          </MainTitleCollections>

          <BlocksGap sections={sections} />

          <DiscoverTheCollection products={products} />
        </div>
      </div>
    </>
  );
};

export default ExpertOvens;
